# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Inference Digital Twin Desktop App

a = Analysis(
    ['desktop/desktop_main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app', 'app'),
        ('contracts', 'contracts'),
        ('artifacts', 'artifacts'),
        ('desktop/assets', 'desktop/assets'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.config',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.main',
        'app.main',
        'app.api',
        'app.api.routes',
        'app.config',
        'app.db',
        'app.orchestrator',
        'app.run_queue',
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'jinja2',
        'jsonschema',
        'pydantic',
        'h11',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='InferenceDigitalTwin',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='desktop/assets/appicon.ico',
)
